included:
  - APNS
  - pusher
  - PusherMainView
  - FCM

opt_in_rules:
- empty_count
- empty_string


disabled_rules:
- identifier_name
- function_parameter_count
- nesting
- todo
- blanket_disable_command

line_length:
    warning: 150
    error: 200
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true

function_body_length:
    warning: 300
    error: 500

function_parameter_count:
    warning: 6
    error: 8

type_body_length:
    warning: 300
    error: 500

file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true

cyclomatic_complexity:
    warning: 25
    error: 25

large_tuple:
    warning: 3
    error: 3

reporter: "xcode"
